### ISSUE TITLE
NetBSD build issue

### ISSUE THREAD

**Issue by 0-wiz-0** [bsdphk/Ntimed#23]
The build with BSD make on NetBSD-7.99.3/amd64 fails with
````
make: make: don't know how to make ntimed-client.1. Stop
````

Using GNU make it fails with:
````
In file included from ntp_packet.c:64:0:
ntimed_endian.h:54:1: error: redefinition of 'be16enc'
 be16enc(void *pp, uint16_t u)
 ^
In file included from /usr/include/amd64/endian.h:3:0,
                 from /usr/include/sys/types.h:98,
                 from /usr/include/stdlib.h:41,
                 from ntp_packet.c:59:
/usr/include/sys/endian.h:203:1: note: previous definition of 'be16enc' was here
 __GEN_ENDIAN_ENC(16, be)
 ^
In file included from ntp_packet.c:64:0:
ntimed_endian.h:63:1: error: redefinition of 'be32enc'
 be32enc(void *pp, uint32_t u)
 ^
In file included from /usr/include/amd64/endian.h:3:0,
                 from /usr/include/sys/types.h:98,
                 from /usr/include/stdlib.h:41,
                 from ntp_packet.c:59:
/usr/include/sys/endian.h:204:1: note: previous definition of 'be32enc' was here
 __GEN_ENDIAN_ENC(32, be)
 ^
````
