### ISSUE TITLE
Requires CFLAGS='-std=gnu99' to compile on at least CentOS 5.11

### ISSUE THREAD

**Issue by joakimfors** [bsdphk/Ntimed#1]
Don't know if you want these trivial issues. However, Ntimed requires CFLAGS='-std=gnu99' to compile on CentOS 5.11 with gcc 4.11. Otherwise it complains about missing NAN:

```
$ make
cc -Wall -Werror   -c -o combine_delta.o combine_delta.c
combine_delta.c: In function ‘CD_AddSource’:
combine_delta.c:204: error: ‘NAN’ undeclared (first use in this function)
combine_delta.c:204: error: (Each undeclared identifier is reported only once
combine_delta.c:204: error: for each function it appears in.)
make: *** [combine_delta.o] Error 1
```

**Comment by joakimfors** [comment]
```
make
cc -Wall -Werror   -c -o combine_delta.o combine_delta.c
combine_delta.c: In function ‘CD_AddSource’:
combine_delta.c:208: error: ‘INFINITY’ undeclared (first use in this function)
combine_delta.c:208: error: (Each undeclared identifier is reported only once
combine_delta.c:208: error: for each function it appears in.)
make: *** [combine_delta.o] Error 1
```

Perhaps the Makefile generation should be patched to include `CFLAGS="-std=gnu99"` instead?

**Comment by technion** [comment]
Now that's a worry. GNU decided that NAN was a GNU extension, but the link in my comment states clearly that INFINITY is part of the C99 standard and should exist everywhere.

Telling a portable program to compile with GNU extensions is not the right approach imo.

You don't by chance have default CFLAGS compiling for std89 or something do you?

**Comment by bsdphk** [comment]
I have changed NAN which strictly speaking is only for float, to nan("") which is for double.

I'm not ever going to add a "-std=gnuanything" option if I can avoid it.
