### ISSUE TITLE
Does not compile on Mac OS X 10.10.1

### ISSUE THREAD

**Issue by joakimfors** [bsdphk/Ntimed#2]
Another, perhaps trivial, compile/make error:

```
$ make
cc -Wall -Werror   -c -o time_stuff.o time_stuff.c
time_stuff.c:67:19: error: conflicting types for 'TS_Nanosec'
struct timestamp *TS_Nanosec(struct timestamp *storage, intmax_t sec, intmax_t nsec)
                  ^
./ntimed.h:124:19: note: previous declaration is here
struct timestamp *TS_Nanosec(struct timestamp *storage,
                  ^
time_stuff.c:153:41: error: format specifies type 'intmax_t' (aka 'long') but the argument has type
      'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
        assert(snprintf(buf, len, "%jd.%09jd", x, y) < len);
                                   ~~~         ^
                                   %llu
/usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                                             ^
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
time_stuff.c:153:44: error: format specifies type 'intmax_t' (aka 'long') but the argument has type
      'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
        assert(snprintf(buf, len, "%jd.%09jd", x, y) < len);
                                       ~~~~~      ^
                                       %09llu
/usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                                             ^
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
3 errors generated.
make: *** [time_stuff.o] Error 1
```

Default compiler used:

```
$ cc -v
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
```

**Comment by bsdphk** [comment]
I have fixed the type-nits which gave compile errors.

I don't think trying to stuff a new PLL into OS/X's kernel is a sound strategy, but I don't have time (or Apple hardware) to research which time-twisting primitives OS/X actually implements, but they would have to be incredibly bad to not be workable for ntimed.

I'm going to follow the same policy as we have in Varnish:  issues/tickets are for actionable bug reports only, so I will close this ticket for now.

**Comment by steakknife** [comment]
For reference should anyone else have spare cycles or another approach, here's how another project tackled this:

http://sourceforge.net/p/ptpd/code/HEAD/tree/trunk/src/dep/sys.c
